apiVersion: apps/v1
kind: Deployment
metadata:
  name: securelink
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: securelink
  template:
    metadata:
      labels:
        app: securelink
    spec:
      containers:
        - name: securelink
          image: securelink:latest
          ports:
            - containerPort: 5173
          env:
            - name: HUNKO_USERS_SERVICE_API_URL
              value: "http://hunko-users:8000"
            - name: HUNKO_USERS_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: securelink-secrets
                  key: hunkoApiKey
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://dashboard.zerologsvpn.com"
            - name: NEXT_PUBLIC_HANKO_API_URL
              value: "https://dashboard.zerologsvpn.com"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: securelink
spec:
  type: NodePort
  selector:
    app: securelink
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30082
      protocol: TCP
