apiVersion: v1
kind: Service
metadata:
  name: securelink
  namespace: securelink
spec:
  type: NodePort
  selector:
    app: securelink
  ports:
  - name: http
    port: 80
    targetPort: 5173
    nodePort: 30082
