# yamllint disable rule:line-length rule:truthy
---
name: CI (docker)

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: securelink

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Compute safe image reference
        id: img
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${GITHUB_REPOSITORY_OWNER,,}"
          NAME="${IMAGE_NAME,,}"
          SAFE_NAME=$(echo "$NAME" | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')
          if [ -z "$SAFE_NAME" ]; then
            echo "IMAGE_NAME resolved to empty" >&2; exit 1
          fi
          IMAGE="${REGISTRY}/${OWNER}/${SAFE_NAME}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "Using image: ${IMAGE}"

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.img.outputs.image }}:latest
            ${{ steps.img.outputs.image }}:sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      # TODO: Add smoke-test with ephemeral Postgres
