name: Build & Push Docker
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # owner в нижнем регистре для GHCR
      - name: Set lowercase owner
        shell: bash
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      # Build image and LOAD it into runner for smoke test (no push yet)
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: app:ci
          load: true

      # Smoke test: run container and curl endpoints
      - name: Run container for smoke test
        run: |
          docker run -d --rm --name db -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=test -p 5432:5432 postgres:16
          docker run -d --rm --name app-ci --link db -p 5173:5173 \
            -e DB=postgresql://postgres:postgres@db:5432/test?sslmode=disable \
            -e MIGRATE_ON_BOOT=1 \
            -e FIRST_ADMIN_EMAIL=admin@example.com \
            -e FIRST_ADMIN_PASSWORD=secret \
            app:ci
          for i in $(seq 1 30); do
            sleep 2
            if curl -fsS http://127.0.0.1:5173/healthz >/dev/null; then break; fi
            if [ $i -eq 30 ]; then echo "healthz failed"; docker logs app-ci; exit 1; fi
          done
          code=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://127.0.0.1:5173/api/auth/login -H "content-type: application/json" -d '{}')
          if [ "$code" = "404" ]; then echo "/api/auth/login returned 404"; docker logs app-ci; exit 1; fi
          curl -c cookie.txt -s -o /dev/null -w "%{http_code}" -X POST http://127.0.0.1:5173/api/auth/login -H "content-type: application/json" -d '{"email":"admin@example.com","password":"secret"}'
          curl -b cookie.txt -H "content-type: application/json" -d '{"name":"test","price":10,"periodDays":30,"trafficMb":null,"active":true}' http://127.0.0.1:5173/api/admin/plans
          curl -fsS http://127.0.0.1:5173/api/pricing | tee pricing.json
          grep '"name":"test"' pricing.json
          docker logs app-ci
          docker stop app-ci
          docker stop db

      # Login to GHCR and PUSH production tags
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/securelink:latest
            ghcr.io/${{ env.OWNER_LC }}/securelink:sha-${{ github.sha }}
