name: Build & Push Docker
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # Build image and LOAD it into runner for smoke test (no push yet)
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: app:ci
          load: true

      # Smoke test: run container and curl endpoints
      - name: Run container for smoke test
        run: |
          docker run -d --rm --name app-ci -p 5173:5173 app:ci
          for i in $(seq 1 30); do
            sleep 2
            if curl -fsS http://127.0.0.1:5173/healthz >/dev/null; then break; fi
            if [ $i -eq 30 ]; then echo "healthz failed"; docker logs app-ci; exit 1; fi
          done
          # API must not be 404
          code=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://127.0.0.1:5173/api/auth/login -H "content-type: application/json" -d '{}')
          if [ "$code" = "404" ]; then echo "/api/auth/login returned 404"; docker logs app-ci; exit 1; fi
          docker logs app-ci
          docker stop app-ci

      # Login to GHCR and PUSH production tags
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/securelink:latest
            ghcr.io/${{ github.repository_owner }}/securelink:sha-${{ github.sha }}

